### ISSUE TITLE
Error: zero-length 'labels' specified

### ISSUE THREAD

**Issue by aganezov** [gavinha/TitanCNA_10X_snakemake#1]
Hello!

I'm trying to utilize `TitanCNA` on 10x dataset of tumor + normal (lloking for clone- and alllele-specifc CNA analysis) that I have and I run into the following issue (when executing the `snakemake -s TitanCNA.snakefile`, with other `snakemake` scripts ran separately and successfully finished):

```
Error in text.default(x = my.x, y = rep(label.y, length(my.x)), labels = rownames(cytoband),  : 
  zero-length 'labels' specified
Calls: plotIdiogram.hg38 -> text -> text.default
```

This is weird as the `cytoband` value seems to be fine (as I've modified the code to output `cytoband` variable value right before the `plotIdiogram.hg38` function call (I have `hg38` build), and the variable seems to be fine (i.e., resembling the cytoband file contents)).

I wonder if you've encountered this issue being reported before, and that would be a fix for it (as fat as I understand, the actual TitanCNA magic works fine, and only the plotting is an issue, which I don't care for that much). 

Again, thank you for an awesome tools and so much work put into usability of it. I'm 99% there and hope you can help me achieve the 100%!

**Comment by gavinha** [comment]
Hi @aganezov 

I have transferred this issue here because the snakemake pipelines and the R scripts are from this repo.

To help me figure out your issue, can you tell me what your genome naming convention is?
UCSC (e.g. "chr1") or NCBI (e.g. "1")?
It looks like you are looking for NCBI, but I want to confirm.

At the moment, the provided cytoband file provided in this repo is using UCSC names
https://github.com/gavinha/TitanCNA_10X_snakemake/blob/master/data/cytoBand_hg38.txt

Still, [titanCNA_v1.15.0_TenX.R](https://github.com/gavinha/TitanCNA_10X_snakemake/blob/master/code/titanCNA_v1.15.0_TenX.R) should be able to handle this.  What might be happening is that the chromosome names are not matching and so it is not reading the cytoband file correctly.  I can look into this.

The plots can be informative for inspecting your results and for confirming or selecting optimal solutions. I encourage you to look at the plots once we can sort this issue out.

Best,
Gavin

**Comment by gavinha** [comment]
Hi @aganezov 

As part of the last commit, I uncommented a line that should help with figuring out the chromosome naming style the cytobands. If this doesn't work, please re-open this issue.

There are also many other changes in the snakemake pipeline so hopefully things should still work.  If not, please make another issue here and I'll work through it.

Thanks,
Gavin

**Comment by aganezov** [comment]
@gavinha 
The bam file has the reads aligned with LongRanger to the `GRCh38` with the `chr` prefix on chromosomal names (i.e., the UCSC convention on the hg38 build).

I have the `genomeBuild` parameter in the `config.yaml` specified as `hg38` (I've tried setting it to `GRCh38`, but R script had an error with it). 

The `genomeStyle` parameter is set to `NCBI`, but I believe this shall only affect the output labeling (though, if this is the issue, I'll be happy to rerun it with `UCSC` being specified).

I'll try do update the 10x repository version on my machine and rerun the experiment, and will let you know if the issue persists.

**Comment by aganezov** [comment]
@gavinha  
I've reran the 10x pipeline (using the latest version of the repository), and it still failed with an error, but a different one (though, I think somewhat related). 

Below is a log file excerpt:

```
locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats4    methods   stats     graphics  grDevices utils    
[8] datasets  base     

other attached packages:
 [1] SNPchip_2.24.0       doMC_1.3.5           iterators_1.0.10    
 [4] foreach_1.4.4        dplyr_0.7.4          GenomicRanges_1.32.7
 [7] GenomeInfoDb_1.16.0  IRanges_2.14Analyzing sample as sex: female
Running TITAN...
titan: Loading data and phasing information results/phasedCounts/tumCounts/tumor_sample_1.tumCounts.txt
titan: Loading GC content and mappability corrected log2 ratios...
titan: Extracting read depth...
Removed 0 centromeric positions
Removed Chrs: 
titan: Loading default parameters
Using 1 cores.
titan: Running HMM...
fwdBack: Iteration 1 chr: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 
Using Coordinate Descent iteration 14 with Fval=-4799633 and n=0.0243 (map), s=[0.00016], phi=1.889
fwdBack: loglik=869059.2510
fwdBack: priorN=-1.9500
fwdBack: priorS=-6.9387
fwdBack: priorVar=-113483.5869
fwdBack: priorVarR=-30956.2023
fwdBack: priorPhi=-0.1776
fwdBack: priorPiG=606.8460
fwdBack: priorPiZ=0.0000
fwdBack: EM iteration 1 complete loglik=725217.2414
fwdBack: Elapsed time for iteration 1: 2.5637m
fwdBack: Iteration 2 chr: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 
Using Coordinate Descent iteration 11 with Fval=-4816120 and n=0.01139 (map), s=[0.00039], phi=1.886
fwdBack: loglik=2440659.1729
fwdBack: priorN=-2.6947
fwdBack: priorS=-6.0622
fwdBack: priorVar=-68113.3196
fwdBack: priorVarR=-37621.2651
fwdBack: priorPhi=-0.1796
fwdBack: priorPiG=606.8460
fwdBack: priorPiZ=0.0000
fwdBack: EM iteration 2 complete loglik=2335522.4978
fwdBack: Elapsed time for iteration 2: 2.3637m
fwdBack: Iteration 3 chr: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 
Using Coordinate Descent iteration 11 with Fval=-4797134 and n=0.009872 (map), s=[0.00042], phi=1.887
fwdBack: loglik=2494410.8787
fwdBack: priorN=-2.8363
fwdBack: priorS=-5.9778
fwdBack: priorVar=-48604.8573
fwdBack: priorVarR=-43436.4689
fwdBack: priorPhi=-0.1788
fwdBack: priorPiG=606.8460
fwdBack: priorPiZ=0.0000
fwdBack: EM iteration 3 complete loglik=2402967.4055
fwdBack: Elapsed time for iteration 3: 2.3$dens.bw
[1] 0.2150319

$scat
[1] 1.404258

$S_Dbw
[1] 1.61929

15 16 17 18 19 20 21 22 23 
Using Coordinate Descent iteration 11 with Fval=-4806905 and n=0.0079 (map), s=[0.00044], phi=1.89
fwdBack: loglik=2522705.5937
fwdBack: priorN=-3.0570
fwdBack: priorS=-5.9277
fwdBack: priorVar=-48813.1415
fwdBack: priorVarR=-45744.8305
fwdBack: priorPhi=-0.1770
fwdBack: priorPiG=606.8460
fwdBack: priorPiZ=0.0000
fwdBack: EM iteration 4 complete loglik=2428745.3060
fwdBack: Elapsed time for iteration 4: 2.2990m
fwdBack: Iteration 5 chr: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 
Using Coordinate Descent iteration 11 with Fval=-4815979 and n=0.007314 (map), s=[0.00049], phi=1.891
fwdBack: loglik=2537465.8298
fwdBack: priorN=-3.1336
fwdBack: priorS=-5.8294
fwdBack: priorVar=-50092.4243
fwdBack: priorVarR=-47391.0416
fwdBack: priorPhi=-0.1762
fwdBack: priorPiG=606.8460
fwdBack: priorPiZ=0.0000
fwdBack: EM iteration 5 complete loglik=2440580.0707
fwdBack: Elapsed time for iteration 5: 2.2885m
fwdBack: Iteration 6 chr: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 
Using Coordinate Descent iteration 11 with Fval=-4822110 and n=0.007213 (map), s=[0.00054], phi=1.892
fwdBack: loglik=2544948.8076
fwdBack: priorN=-3.1474
fwdBack: priorS=-5.7322
fwdBack: priorVar=-50880.3886
fwdBack: priorVarR=-48283.3024
fwdBack: priorPhi=-0.1758
fwdBack: priorPiG=606.8460
fwdBack: priorPiZ=0.0000
fwdBack: EM iteration 6 complete loglik=2446382.9071
fwdBack: Elapsed time for iteration 6: 2.2876m
fwdBack: Iteration 7 chr: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 
Using Coordinate Descent iteration 11 with Fval=-4825292 and n=0.007302 (map), s=[0.00059], phi=1.892
fwdBack: loglik=2549004.2457
fwdBack: priorN=-3.1352
fwdBack: priorS=-5.6454
fwdBack: priorVar=-51342.8582
fwdBack: priorVarR=-48798.2391
fwdBack: priorPhi=-0.1756
fwdBack: priorPiG=606.8460
fwdBack: priorPiZ=0.0000
fwdBack: EM iteration 7 complete loglik=2449461.0383
fwdBack: Elapsed time for iteration 7: 2.2993m
fwdBack: Iteration 8 chr: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 
Using Coordinate Descent iteration 11 with Fval=-4827516 and n=0.007438 (map), s=[0.00064], phi=1.892
fwdBack: loglik=2551278.5987
fwdBack: priorN=-3.1168
fwdBack: priorS=-5.5699
fwdBack: priorVar=-51751.9074
fwdBack: priorVarR=-49272.4758
fwdBack: priorPhi=-0.1754
fwdBack: priorPiG=606.8460
fwdBack: priorPiZ=0.0000
fwdBack: EM iteration 8 complete loglik=2450852.1993
fwdBack: Elapsed time for iteration 8: 2.2889m
fwdBack: Total elapsed time: 19.0705m
Using 1 cores.
Writing results to results/titan/titanCNA_ploidy2/tumor_sample_1_cluster1.titan.txt,
	results/titan/titanCNA_ploidy2/tumor_sample_1_cluster1.segs.txt,
	results/titan/titanCNA_ploidy2/tumor_sample_1_cluster1.params.txt
titan: Saving parameters to results/titan/titanCNA_ploidy2/tumor_sample_1_cluster1.params.txt
Error in seqlevelsStyle(as.character(x)) : 
  No seqlevels present in this object.
Calls: setGenomeStyle -> %in% -> seqlevelsStyle -> seqlevelsStyle
Execution halted
```

I've used the `UCSC` value for the `genomeStyle` parameter in the config.

**Comment by aganezov** [comment]
@gavinha 
P.S. I do not think that I have do not have permission to re-open the issue (either due to it being relocated here in the first place, or for some other reason).

**Comment by aganezov** [comment]
Hey @gavinha just wanted to let you know, that the execution finished just fin after updating both `TitanCNA_10x` and `TitanCNA`.
