### ISSUE TITLE
bxtools

### ISSUE THREAD

**Issue by jgockley62** [gavinha/TitanCNA_10X_snakemake#2]
Hey Gavin,

I keep getting an error when I try and run the snakemake workflow:

>snakemake -s TitanCNA.snakefile -np
  _Building DAG of jobs...
  MissingInputException in line 33 of 
  <PATH>/TitanCNA/TitanCNA.snakefile:
  Missing input files for rule runTitanCNA:
  results/moleculeCoverage/tumor_sample_1/tumor_sample_1.BXcounts.txt
  results/moleculeCoverage/tumor_sample_1/tumor_sample_1.params.txt_

In my understanding this script should run bxtools to tile counts across the windows specified in the provided folder of windows right? Any idea on what might be going on?

**Comment by gavinha** [comment]
Hi @jgockley62 

While I was testing, I commented out the `include: "moleculeCoverage.snakefile"` line for the `TitanCNA.snakefile` so it wasn't running the molecule coverage step.  

Best,
Gavin
