### ISSUE TITLE
titanCNA_v1.21.0_TenX.R

### ISSUE THREAD

**Issue by mzwaig** [gavinha/TitanCNA_10X_snakemake#5]
Hi Gavin,

I'm trying to run titanCNA_v1.21.0_TenX.R and I keep getting the following error message in the log file (full file attached).

Analyzing sample as sex: male
Running TITAN...
titan: Loading data and phasing information results/phasedCounts/tumCounts/tumor_sample_1.tumCounts.txt
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function 'select' for signature '"data.table"'
Calls: loadHaplotypeAlleleCounts ... standardGeneric -> eval -> eval -> eval -> select -> <Anonymous>
Execution halted

I can't figure out at which step the error is occurring. Any ideas? 

Thanks,
Melissa

[tumor_sample_1_cluster1.log]
(https://github.com/gavinha/TitanCNA_10X_snakemake/files/3473785/tumor_sample_1_cluster1.log)

**Comment by gavinha** [comment]
Hi @mzwaig 

This might be related to a library import error.  Can you check the `sessionInfo()` to make sure that `dplyr` is loaded?

-Gavin

**Comment by mzwaig** [comment]
Hi @gavinha,

It looks like it's loading properly. Lines 50 abd 68 of the log file. 

[tumor_sample_1_cluster1.log](https://github.com/gavinha/TitanCNA_10X_snakemake/files/3481938/tumor_sample_1_cluster1.log)

Melissa

**Comment by gavinha** [comment]
I just tried this command again to see if I could reproduce the error. It worked on my end and this is my `sessionInfo()` 

It appears I am using `dplyr_0.8.0.1`.  I'm not sure if this is the issue for you. I can try to update to the latest version (0.8.3) and test it. 

Also, are you setting `libdir`? I'm wondering if there isn't anything related to scope of packages between loading the installed `TitanCNA` package vs sourcing all the individual R files.

```> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

Matrix products: default
BLAS/LAPACK: /app/easybuild/software/OpenBLAS/0.2.18-GCC-5.4.0-2.26-LAPACK-3.6.1/lib/libopenblas_prescottp-r0.2.18.so

Random number generation:
 RNG:     Mersenne-Twister
 Normal:  Inversion
 Sample:  Rounding

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
 [1] SNPchip_2.30.0       doMC_1.3.5           iterators_1.0.10     foreach_1.4.4        dplyr_0.8.0.1        GenomicRanges_1.36.0 GenomeInfoDb_1.20.0  IRanges_2.18.0
 [9] S4Vectors_0.22.0     BiocGenerics_0.30.0  data.table_1.12.2    TitanCNA_1.20.1```

**Comment by mzwaig** [comment]
I figured it out. I had Titan installed through conda which didn't work. I downloaded it locally and set libdir. It looks like it's running well!

Thanks for your help,
Melissa
